[package]
name = "dicebot"
version = "0.2.0"
authors = ["Kalle Rennes <kalle@kallerennes.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
pom = "3.1.0"
rocket = "0.4.4"
itertools = "0.8"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["json"]
