[package]
name = "dicebot"
version = "0.1.0"
authors = ["Kalle Rennes <kalle@kallerennes.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
pom = "3.0.2"
rocket = "0.4.2"
itertools = "0.8"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]
